<%@ page language="java" contentType="text/html; charset=US-ASCII"
	pageEncoding="US-ASCII"%>
<%@ page import="java.util.*"%>
<!DOCTYPE >
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<link href="CSS/page_style.css" rel="stylesheet" type="text/css" />
<link href="friendpage_style.css" rel="stylesheet" type="text/css" />
<title>About RockQuiz</title>
</head>
<body>
	<div id="wrapper">
		<div id="inner">
			<div id="header">
				<h1>About RockQuiz</h1>
				<h3><%=new Date()%></h3>
				<div id="nav">
					<h2>
						<a href="home.jsp">Home</a> | <a href="Logout">Log out</a>
					</h2>
				</div>
			</div>
			<div id="body">
				<div class="inner">
					<p>
						<b><i>Required Feature</i></b>
					</p>
					<ul>
						<li>Question Type:
							<ul>
								<li>Question-Response</li>
								<li>Fill In the Blank</li>
								<li>Multi-Choice</li>
								<li>Picture-Response Questions</li>
							</ul>
						</li>
						<li>Quiz Properties and options:
							<ul>
								<li>Random Question(TODO)</li>
								<li>One Page vs Multiple Page</li>
								<li>Immediate Correction</li>
								<li>Practice Mode(TODO)</li>
							</ul>
						</li>
						<li>Scoring:
							<ul>
								<li>Basic score display for each quiz</li>
								<li>Separate scoring for Multi-Answer</li>
								<li>Quiz history about how users did in this quiz</li>
								<li>Rank based on scoring (top scorer)</li>
							</ul>
						</li>
						<li>User:
							<ul>
								<li>Create new account</li>
								<li>Login/Password encrypted</li>
							</ul>
						</li>
						<li>Friends:
							<ul>
								<li>Send/Cancel/Confirm friend request</li>
								<li>Remove friend</li>
								<li>Search users</li>
							</ul>
						</li>
						<li>Mail Messages:
							<ul>
								<li>Friend request</li>
								<li>Challenge request</li>
								<li>Simple message</li>
							</ul>
						</li>
						<li>History
							<ul>
								<li>Quiz performance</li>
							</ul>
						</li>
					</ul>


					<p>
						<b><i>Recommended Feature</i></b>
					</p>
					<ul>
						<li>Achievements
							<ul>
								<li>Add achievement whenever finishing a quiz</li>
								<li>Achievement list</li>
							</ul>
						</li>
						<li>Administration</li>
						<ul>
							<li>Create announcements</li>
							<li>Remove user accounts</li>
							<li>Remove quizzes</li>
							<li>Clear all history information for a certain quiz</li>
							<li>Change users' rights</li>
							<li>See site statistics</li>
						</ul>
					</ul>


					<p>
						<b><i>Extension</i></b>
					</p>
					<ul>
						<li>categorize quiz</li>
						<li>categorize questions(TODO)</li>
						<li>search by category(TODO)</li>
						<li>Question Type:
							<ul>
								<li>Multi-Answer Question(ordered/unordered answer)</li>
								<li>Multiple Choice With Multiple Answers</li>
								<li>Timed Questions(check if isOnePage is true, use
									javascript to disable this field)</li>
								<li>Autogenerated Questions(TODO)</li>
								<li>Graded Question(TODO)</li>
							</ul>
						</li>
						<li>Tags and Categories:
							<ul>
								<li>categorize quiz(TODO)</li>
								<li>categorize questions(TODO)</li>
								<li>search by category(TODO)</li>
							</ul>
						</li>
						<li>Non-Registered Access</li>
						<li>Privacy Setting</li>

						<li>Quiz Editing(TODO)</li>
						<li>Rating and Review System(TODO)</li>
						<li>Reporting System(TODO)</li>
						<li>Error Handling(TODO-MUST DO)</li>
						<li>Cookies(TODO)</li>
						<li>Privacy Setting(TODO)</li>
					</ul>

				</div>

			</div>
		</div>
</body>
</html>